/**
 * Generates supabase/seed.sql from the canonical seed data in lib/data/spots.ts,
 * so the bundled fallback and the database can never drift.
 *
 * Run: npm run seed:sql
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { COLLECTIONS, SPOTS } from "../lib/data/spots";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const qOrNull = (s: string | null) => (s === null ? "null" : q(s));
const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`;

const spotValues = SPOTS.map((s, i) =>
  [
    q(s.id),
    q(s.name),
    q(s.category),
    q(s.area),
    s.coords ? String(s.coords.lat) : "null",
    s.coords ? String(s.coords.lng) : "null",
    String(s.priceBand),
    q(s.priceEstimate),
    q(s.blurb),
    s.tags.length ? arr(s.tags) : "'{}'::text[]",
    `${q(JSON.stringify(s.hours))}::jsonb`,
    qOrNull(s.address),
    qOrNull(s.phone),
    qOrNull(s.website),
    qOrNull(s.bookingUrl),
    "'{}'::text[]",
    String(s.rating),
    String(s.reviewCount),
    String(i),
    q(s.updatedAt),
    qOrNull(s.googlePlaceId),
  ].join(", ")
).map((v) => `  (${v})`);

const collectionValues = COLLECTIONS.map((c, i) =>
  `  (${[q(c.key), q(c.label), q(c.desc), q(c.icon), q(c.paletteKey), c.spotIds === null ? "'free'" : "null", String(i)].join(", ")})`
);

const memberValues = COLLECTIONS.flatMap(
  (c) => (c.spotIds ?? []).map((id, pos) => `  (${q(c.key)}, ${q(id)}, ${pos})`)
);

const sql = `-- Generated by scripts/generate-seed.ts — do not edit by hand.
-- Run after supabase/migrations/0001_init.sql.

insert into public.spots
  (id, name, category, area, lat, lng, price_band, price_estimate, blurb, tags,
   hours, address, phone, website, booking_url, photos, rating, review_count,
   sort_order, updated_at, google_place_id)
values
${spotValues.join(",\n")}
on conflict (id) do update set
  name = excluded.name, category = excluded.category, area = excluded.area,
  lat = excluded.lat, lng = excluded.lng, price_band = excluded.price_band,
  price_estimate = excluded.price_estimate, blurb = excluded.blurb,
  tags = excluded.tags, hours = excluded.hours, address = excluded.address,
  phone = excluded.phone, website = excluded.website,
  booking_url = excluded.booking_url, rating = excluded.rating,
  review_count = excluded.review_count, sort_order = excluded.sort_order,
  updated_at = excluded.updated_at, google_place_id = excluded.google_place_id;

insert into public.collections (key, label, description, icon, palette_key, rule, sort_order)
values
${collectionValues.join(",\n")}
on conflict (key) do nothing;

insert into public.collection_spots (collection_key, spot_id, position)
values
${memberValues.join(",\n")}
on conflict (collection_key, spot_id) do nothing;
`;

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "supabase", "seed.sql");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, sql, "utf8");
console.log(`Wrote ${out}`);
